# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**/README.md'
    tags:
      - v1.*

jobs:
  Compile:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Compile with Gradle
        run: gradle compileTestJava


  Test:
    needs: [Compile]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Test with Gradle
        run: gradle test

      - name: Publish Test Report
        uses: actions/upload-artifact@v2
        with:
          name: testReport
          path: build/reports/tests/test/*


  Assemble:
    needs: [Test]
    runs-on: ubuntu-latest

    outputs:
      output1: ${{ steps.step1.outputs.test }}

    env:
      DIR_NAME: BuildJar

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Assemble with Gradle
        run: gradle assemble

      - name: Upload Jar File
        uses: actions/upload-artifact@v2
        with:
          name: $DIR_NAME
          path: build/libs

      - name: Output Env Var
        id: step1
        run: echo "::set-output name=test::$DIR_NAME"


  Release:
    needs: [ Assemble ]
    runs-on: ubuntu-latest

    if: github.event_name == 'push' && contains(github.ref, '/tags/v')

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Download Artifact
        uses: actions/download-artifact@v2

      - name: Display structure of downloaded files
        run: ls -R

      - name: Prepare file name
        id: vars
        run: |
          echo ::set-output name=version::"$(gradle -q resolveProperties --prop=rootProject.version)"
          echo ::set-output name=project_name::"$(gradle -q resolveProperties --prop=rootProject.name)"

      - name: TEST
        run: echo ${{ steps.vars.outputs.VERSION }}
        env:
          VERSION: ${{ steps.vars.outputs.VERSION }}

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./$DIR_NAME/Lab4-1.0-SNAPSHOT.jar
        env:
          DIR_NAME: ${{needs.job1.outputs.output1}}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERSION: ${{ steps.vars.outputs.VERSION }}
          PROJECT_NAME: ${{ steps.vars.outputs.project_name }}